{
  "name": "Tuya Addressable Strip",
  "description": "Reverse engineering on Tuya payload for addressable LED strips. Useful to integrate with Home Assistant",
  "version": "1.0.15",
  "slug": "tuya_addressable_strip",
  "init": false,
  "image": "iryu54/tuya-addressable-strip",
  "ports": {
    "5845/tcp": 5845
  },
  "arch": [
    "amd64"
  ],
  "options": {
    "TUYA_SECRET_KEY": "",
    "TUYA_ACCESS_KEY": "",
    "APIKEY": ""
  },
  "schema": {
    "server_port": "int",
    "MY_VARIABLE": "str",
    "ANOTHER_VARIABLE": "str",
    "EXTRA_VARIABLE": "str"
  }
}
