name: "Tuya Addressable Strip"
description: "Reverse engineering on tuya payload for addressable led strips. Usefull to integrate with home assistant"
version: "1.0.9"
slug: "tuya_addressable_strip"
init: false
image: ghcr.io/clabroche/tuya-addressable-strip
arch:
  - amd64

