name: Publish to Registry
on:    
  push:
    tags:
      - '*'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - id: package-json
      name: Read package.json
      run: |
        echo packageJSON=$(cat package.json) >> $GITHUB_OUTPUT

    - name: Publish
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        tags: | 
          ghcr.io/clabroche/docker-registry/tuya-addressable-strip:latest
          ghcr.io/clabroche/docker-registry/tuya-addressable-strip:${{fromJson(steps.package-json.outputs.packageJson).version}}
        push: true
