name: Publish to Registry
on:    
  push:
    tags:
      - '*'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - id: package-json
      name: Read package.json
      run: |
        echo packageJSON=$(cat package.json) >> $GITHUB_OUTPUT

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Publish
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile.standalone
        tags: | 
          iryu54/tuya-addressable-strip:latest
          iryu54/tuya-addressable-strip:${{fromJson(steps.package-json.outputs.packageJson).version}}
        push: true
